FROM rocker/r-ver:4.3.1

RUN R -e 'install.packages(c( \
"dplyr", \
"tidyr", \
"readr", \
"purrr", \
"stringr", \
"ggplot2", \
"jsonlite", \
"vegan", \
"pheatmap", \
"tibble", \
"knitr", \
"rmarkdown" \
), repos="https://cloud.r-project.org")'
